import { FC } from 'react';
import type { Metadata } from 'next';
import { DataTable } from '@imerss/inat-curated-species-list';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: FC = () => {
  return (
    <html lang="en">
      <body>
        <DataTable />
      </body>
    </html>
  );
};

export default RootLayout;

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }
